function [net, info] = get_lstm_net(param, x_train, y_train)
%% LSTM network training

% Define LSTM network
input_size = size(x_train{1}, 1);
num_hidden_units = 50;
num_responses = 2;% numel(categories(train_y));
% info_vehs.num_antenna * info_bs.num_antenna;

cr = custom_regression;
cr.Mt = param.bs.num_antenna;
cr.Mr = param.veh.num_antenna;

layers = [ ...
    sequenceInputLayer(input_size)
    lstmLayer(num_hidden_units, 'OutputMode', 'sequence')
    dropoutLayer(0.2)
    lstmLayer(num_hidden_units, 'OutputMode', 'last')
    dropoutLayer(0.2)
    fullyConnectedLayer(num_responses)
    cr]; % cr / regressionLayer

max_epochs = 400;
mini_batch_size = numel(x_train);

options = trainingOptions('adam' , ...
    'ExecutionEnvironment', 'cpu', ...
    'GradientThreshold', 1, ...
    'LearnRateSchedule','none', ...
    'LearnRateDropPeriod',50, ...
    'LearnRateDropFactor',0.9, ...
    'InitialLearnRate', 0.05, ...
    'MaxEpochs', max_epochs, ...
    'MiniBatchSize', mini_batch_size, ...
    'SequenceLength', 'longest', ...
    'Shuffle', 'once', ...
    'Verbose', 1, ...
    'Plots', 'none');

% Train network
[net, info] = trainNetwork(x_train, y_train, layers, options);
end

